# Generated by Django 4.1.7 on 2023-03-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='user',
            name='apellidos',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
