# Generated by Django 4.1.7 on 2023-03-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_usuario_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='Usuario',
        ),
    ]
