# Generated by Django 4.1.7 on 2023-03-26 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_usuario_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
