# Generated by Django 4.1.7 on 2023-03-31 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_user_apellidos_alter_user_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asunto', models.CharField(default='', max_length=50)),
                ('descripcion', models.CharField(default='', max_length=200)),
                ('deleted', models.BooleanField(default=False)),
                ('associat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues_associado', to='polls.user')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues_creadas', to='polls.user')),
                ('vigilant', models.ManyToManyField(related_name='issues_vigiladas', to='polls.user')),
            ],
        ),
    ]
