# Generated by Django 4.1.7 on 2023-04-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nombre',
        ),
    ]
