# Generated by Django 4.1.7 on 2023-04-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_equipo_miembro_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
