# Generated by Django 4.1.7 on 2023-04-07 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0017_alter_equipo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro_equipo',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
