# Generated by Django 4.1.7 on 2023-04-07 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0018_alter_miembro_equipo_miembro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='vigilant',
            field=models.ManyToManyField(default='', related_name='issues_vigiladas', to=settings.AUTH_USER_MODEL),
        ),
    ]
