# Generated by Django 4.1.7 on 2023-04-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
