# Generated by Django 4.1.7 on 2023-04-12 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0023_issue_deadline_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='vigilant',
            field=models.ManyToManyField(related_name='issues_vigiladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deadline', models.DateTimeField()),
                ('motivo', models.CharField(default='', max_length=200)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='polls.issue')),
            ],
        ),
    ]
