# Generated by Django 4.1.7 on 2023-04-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_comentario_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='reason_blocked',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
