# Generated by Django 4.1.7 on 2023-04-12 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_watcher'),
        ('polls', '0024_alter_issue_vigilant_deadline'),
        ('polls', '0025_issue_blocked_issue_reason_blocked'),
    ]

    operations = [
    ]
