# Generated by Django 4.1.7 on 2023-04-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_watcher'),
        ('polls', '0025_issue_blocked_issue_reason_blocked'),
    ]

    operations = [
    ]
