# Generated by Django 4.1.7 on 2023-04-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_merge_20230412_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=1, max_length=2),
        ),
    ]
