# Generated by Django 4.1.7 on 2023-04-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_issue_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='blocked',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='prioridad',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=1, max_length=2, null=True),
        ),
    ]
