# Generated by Django 4.1.7 on 2023-05-17 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0032_alter_actividad_issue_issue_alter_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad_issue',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_hechas', to=settings.AUTH_USER_MODEL),
        ),
    ]
