NUEVO = 1
EN_PROCESO = 2
FINALIZADO = 3
CANCELADO = 4
NECESITA_INFORMACION= 5
LISTA_PARA_TESTEAR= 6

ESTADOS = [
    (NUEVO, 1),
    (EN_PROCESO, 2),
    (FINALIZADO, 3),
    (CANCELADO, 4),
    (NECESITA_INFORMACION, 5),
    (LISTA_PARA_TESTEAR, 6),
]