openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8000/api
paths:
  /users:
    get:
      summary: Devuelve todos los usuarios
      operationId: get_users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /users/login/:
    post:
      summary: Iniciar sesión de usuario
      operationId: user_login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Se ha iniciado sesion correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: No se han proporcionado todos los datos
        '404':
          description: Usuario o contraseña incorrectos
  /users/register:
    post:
      summary: Registro de usuario
      operationId: user_registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
              required:
                - username
                - password
                - email
      responses:
        '201':
          description: El usuario se ha registrado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'
        '400':
          description: No se han introducido todos los datos
        '409':
          description: El usuario ya existe
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        password:
          type: string
        last_login:
          type: string
          format: date-time
        is_superuser:
          type: boolean
        username:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        is_staff:
          type: boolean
        is_active:
          type: boolean
        date_joined:
          type: string
          format: date-time
        groups:
          type: array
          items:
            type: string
        user_permissions:
          type: array
          items:
            type: string