export const styles = {
    mainScreen: {
        display: "flex",
        flexDirection: "column",
        padding: "0px",
        window: "100%",
        height: "100%",
        backgroundColor: "#F5F5F5",
    },
    upperContainer: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        backgroundColor: "rgb(216, 222, 233)",
        height: "50px",
        width: "100%",
        verticalAlign: "middle",
        alignItems: "center",
    },
    lateralBar: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
        backgroundColor: "rgb(59, 66, 81)",
        height: "100%",
        width: "18%",
    },
    mainContainer: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        backgroundColor: "white",
        height: "95vh",
        width: "100%",
    },
    containerBlock: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "flex-start",
        backgroundColor: "white",
        width: "100%",
        padding:"30px"
    },
    containerBlockFilter: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "flex-start",
        backgroundColor: "white",
        alignItems: "left",
        width: "10%",
    }, 
    lateralSuperior: {
    
    },
    lateralInferior: {

    },
    textLateral: {
        color: "white",
        fontWeight: "bold",
        fontSize: "15px",
        font: "inherit",
        textAlign: "Times New Roman",
        paddingLeft: "10px",
        fontFamily: "serif",
    },
    nombreLateral: {
        color: "white",
        fontWeight: "bold",
        fontSize: "15px",
        font: "inherit",
        textAlign: "Times New Roman",
        backgroundColor: "rgb(46, 52, 64)",
        margin: "0px",
        fontFamily: "sans-serif",
        color: "white",
    },
    barraFiltro: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        paddingBottom: "20px",
        paddingTop: "20px",
        verticalAlign: "middle",
    },
    tablaContainer: {
        display: "flex",
        flexDirection: "column",
        width: "100%",
    },
    tablaContainerFilters: {
        display: "left",
        flexDirection: "column",
        width: "70%",
    },
    fila: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        paddingTop:"10px",
        paddingBottom:"10px",
        paddingLeft:"20px",
    },
    filaIssue: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        paddingTop:"10px",
        paddingBottom:"10px",
        paddingLeft:"20px",
        backgroundColor: "#f9f9fb",
        borderRadius: "5px",
        marginBottom: "10px",
        width: "100%",
    },
    columna: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        width: "5%",
    },
    columnaTexto: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        width: "50%",
    },
    inputBuscador: {
        boxSizing: "border-box",
        paddingRight: "25px",
        backgroundColor: "#fff",
        borderWidth: "2px",
        borderColor: "#d8dee9",
        borderRadius: "3px",
        color:"#4c566a",
        margin: "0px",
        padding: "0.3rem 2rem 0.3rem 0.95rem",
        width: "100%",
        borderStyle: "solid",
    },
    newIssueButton: {
        borderColor: "white",
        borderWidth: "0px",
        borderRadius: "3px",
        backgroundColor: "#83eede",
        padding: "0.7rem 2rem",
    },
}
