name: Deploy to Fly and Run Commands
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Fly CLI
        uses: flyctl/actions/setup-flyctl@v1
        with:
          api_token: ${{ secrets.FLY_API_TOKEN }}
      - name: Deploy to Fly
        run: |
          flyctl deploy
      - name: Run commands on Fly
        run: |
          flyctl ssh console -a it12casw-backend --command "cd code && python manager.py migrate && exit"


