name: Fly Deploy
on:
  push:
    branches:
      - Deploy-Fly.io
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy backend --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
       - run: flyctl ssh console -a it12casw-backend --command "cd code && python manager.py migrate && exit"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

