name: Fly Deploy
on:
  push:
    branches:
      - Deploy-Fly.io
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy backend --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - run: fly ssh console
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - run: cd code
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - run: python manage.py migrate
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - run: exit
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
